version: '3.1'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action_server:  
    image: rasa/rasa_core_sdk:latest  
    ports:  
      - 5055:5055  
    volumes:  
      - ./actions:/app/actions  
    command:  
      - rasa  
      - run  
      - actions